openapi: 3.0.0
info:
  title: member-api
  description: API de gestion des associations et des membres de l'EMA
  version: 0.1.0
  
servers: 
  - url: https://api.cercle-des-eleves.fr/member
    description: URL de l'API en prod (qui ne sera pas ça)

paths:
  /associations:
    get:
      tags:
      - "association"
      description: retourne un liste d'associations.
      responses:
        200:
          description: un table JSON de l'ID et du nom des associations.
    post:
      tags: 
      - association
      description: create an association.
      responses:
        201:
          description: nothing for now
  
  /association/{associationId}:
    get:
      tags: 
      - association
      parameters: 
      - name: associationId
        in: path
        required: true
        description: Id de l'association à retourner.
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Retourne une association en JSON
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Association'
          
components:
  schemas:
    Association:
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: Cercle Des Elèves
      # Both properties are required
      required:  
        - id
        - name